<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Origami">
      <HintPath>C:\Users\LENOVO\.nuget\packages\prowl.origami\3.5.0\lib\net10.0\Origami.dll</HintPath>
    </Reference>
    <Reference Include="Paper">
      <HintPath>C:\Users\LENOVO\.nuget\packages\prowl.paper\3.5.0\lib\net10.0\Paper.dll</HintPath>
    </Reference>
    <Reference Include="Vector">
      <HintPath>C:\Users\LENOVO\.nuget\packages\prowl.vector\3.5.0\lib\net10.0\Vector.dll</HintPath>
    </Reference>
    <Reference Include="Scribe">
      <HintPath>C:\Users\LENOVO\.nuget\packages\prowl.scribe\3.5.0\lib\net10.0\Scribe.dll</HintPath>
    </Reference>
    <Reference Include="Scaffold">
      <HintPath>C:\Users\LENOVO\.nuget\packages\prowl.scaffold\3.5.0\lib\net10.0\Scaffold.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
